services: 
  pgvector:
      image: pgvector/pgvector:0.8.1-pg18-trixie
      container_name: pgvector2
      ports:
        - "5433:5432"
      environment:
        POSTGRES_PASSWORD: ${POSTGRESS_PASSWORD}
        POSTGRES_DB: ${POSTGRESS_DB}
      volumes:
        - pgvector_data:/var/lib/postgresql/data
      networks:
        - backend
networks:
  backend:

volumes:
  pgvector_data:
  